name = "email-manager"
pages_build_output_dir = ".pages-deploy"
compatibility_date = "2025-09-23"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[vars]
NODE_ENV = "production"
