name = "email-manager"
main = ".open-next/worker.js"
compatibility_date = "2025-09-23"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

assets = { directory = ".open-next/assets", binding = "ASSETS" }

[[d1_databases]]
binding = "DB"
database_name = "email-manager-auth"
database_id = "e770dfa2-1032-4a12-b0fb-52e77f5319e8"

[vars]
NODE_ENV = "production"
